data:
  evfile : './PKS2155_data/PKS2155.lst'
  scfile : './PKS2155_data/L211025154921445A2D9929_SC00.fits'
  ltcube : 'ltcube_00.fits'

binning:
  roiwidth   : 12.0
  binsz      : 0.08
  binsperdec : 8

selection :
  emin : 100
  emax : 300000
  tmin : 241401601
  tmax : 257385601
  zmax    : 105
  evclass : 128
  evtype  : 3
  target : 'PKS 2155-304'

gtlike:
  edisp : True
  irfs : 'P8R2_SOURCE_V6'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 12.0
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'
  isodiff  : '$FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_v06.txt' 
  catalogs: gll_psc_v16.fit
  
fileio:
  usescratch: False
  outdir : PKS2155_data