data:
  evfile : events_PKS.txt
  scfile : L211025154921445A2D9929_SC00.fits
#  ltcube : ltcube_00.fits

binning:
  roiwidth   : 15.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 100000
  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin : 241401601
  tmax : 257385601
  filter  : 'DATA_QUAL>0 && LAT_CONFIG==1'
  target : 'PKS2155-304'

gtlike:
  edisp : True
  edisp_bins : -1
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff']

model:
  src_roiwidth : 20.0
  galdiff  : '$CONDA_PREFIX/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits'
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : ['4FGL-DR3']

components:
  - { selection : { evtype : 4  } } # PSF0
  - { selection : { evtype : 8  } } # PSF1
  - { selection : { evtype : 16 } } # PSF2
  - { selection : { evtype : 32 } } # PSF3

fileio:
   outdir : data
